version: "3.3"
services:
  db:
    volumes:
      - /var/lib/mysql
  api:
    image: registry.digitalocean.com/pooperhub/pooper/api:latest
  frontend:
    image: registry.digitalocean.com/pooperhub/pooper/frontend:latest
  nginx:
    volumes:
      - /etc/nginx/ssl