version: "3.3"
services:
  db:
    volumes:
      - /var/lib/mysql
  api:
    build:
      context: ./pooper-api
  frontend:
    build:
      context: ./pooper-frontend
      args:
        - API_BASE_URL=${API_BASE_URL}
        - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
        - MAPBOX_ACCESS_TOKEN=${MAPBOX_ACCESS_TOKEN}
  nginx:
    build:
      context: ./pooper-nginx